const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "27842930255";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '1'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_18_02_06_10_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTkyLFxuICAgICAgICAxNzAsXG4gICAgICAgIDIzOSxcbiAgICAgICAgOCxcbiAgICAgICAgMzEsXG4gICAgICAgIDM1LFxuICAgICAgICAxMzMsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMjQ3LFxuICAgICAgICAxNTEsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTM2LFxuICAgICAgICAxMjksXG4gICAgICAgIDQxLFxuICAgICAgICAxODcsXG4gICAgICAgIDEwMixcbiAgICAgICAgNzYsXG4gICAgICAgIDQ2LFxuICAgICAgICAxOTgsXG4gICAgICAgIDIsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMzAsXG4gICAgICAgIDc5LFxuICAgICAgICA5LFxuICAgICAgICA3OSxcbiAgICAgICAgMjA3LFxuICAgICAgICAyOSxcbiAgICAgICAgMTQ0LFxuICAgICAgICAxMjcsXG4gICAgICAgIDE4MixcbiAgICAgICAgNjMsXG4gICAgICAgIDY3XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE1NixcbiAgICAgICAgMjMzLFxuICAgICAgICAxMzAsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMjQ2LFxuICAgICAgICAyMzMsXG4gICAgICAgIDIwNixcbiAgICAgICAgOTMsXG4gICAgICAgIDIxLFxuICAgICAgICAyMDEsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMTk1LFxuICAgICAgICA3OSxcbiAgICAgICAgMTU5LFxuICAgICAgICAyLFxuICAgICAgICA3NSxcbiAgICAgICAgODMsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMTk1LFxuICAgICAgICA5NCxcbiAgICAgICAgNDMsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTI0LFxuICAgICAgICAxNzUsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMjAzLFxuICAgICAgICAxOTMsXG4gICAgICAgIDExOSxcbiAgICAgICAgNTQsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMTEyLFxuICAgICAgICAzM1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTIwLFxuICAgICAgICAxNCxcbiAgICAgICAgMTU3LFxuICAgICAgICAyMzAsXG4gICAgICAgIDE2NixcbiAgICAgICAgMjEyLFxuICAgICAgICAxOTMsXG4gICAgICAgIDExMixcbiAgICAgICAgNDYsXG4gICAgICAgIDc3LFxuICAgICAgICAyNDMsXG4gICAgICAgIDYsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMjEyLFxuICAgICAgICA1NyxcbiAgICAgICAgMyxcbiAgICAgICAgMjIwLFxuICAgICAgICAxMTAsXG4gICAgICAgIDIzLFxuICAgICAgICA1NixcbiAgICAgICAgNTgsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMjEyLFxuICAgICAgICA0NixcbiAgICAgICAgOTMsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTgzLFxuICAgICAgICAyMTUsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMTYyLFxuICAgICAgICA3NyxcbiAgICAgICAgMTExXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDM3LFxuICAgICAgICA0NixcbiAgICAgICAgMTE3LFxuICAgICAgICAxNjQsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMjA2LFxuICAgICAgICAzMCxcbiAgICAgICAgMTUsXG4gICAgICAgIDkzLFxuICAgICAgICA2OSxcbiAgICAgICAgMTcsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMjM5LFxuICAgICAgICAxNjYsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMjEzLFxuICAgICAgICAxNTMsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMjIsXG4gICAgICAgIDYyLFxuICAgICAgICAxNjAsXG4gICAgICAgIDEwNixcbiAgICAgICAgMjIsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMTMyLFxuICAgICAgICAyMCxcbiAgICAgICAgMzAsXG4gICAgICAgIDEzOCxcbiAgICAgICAgNTksXG4gICAgICAgIDEwNSxcbiAgICAgICAgMTc5LFxuICAgICAgICA3M1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTIwLFxuICAgICAgICAyMjksXG4gICAgICAgIDIzMSxcbiAgICAgICAgMTA3LFxuICAgICAgICAyMjMsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMjA2LFxuICAgICAgICAyMDIsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMTgyLFxuICAgICAgICA5NyxcbiAgICAgICAgMTcxLFxuICAgICAgICA5OSxcbiAgICAgICAgMTUsXG4gICAgICAgIDkwLFxuICAgICAgICAxMTIsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMjUsXG4gICAgICAgIDMwLFxuICAgICAgICAxOTQsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMTk1LFxuICAgICAgICAyNDEsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMTA3LFxuICAgICAgICAyMjcsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMjIzLFxuICAgICAgICAyMjksXG4gICAgICAgIDMxLFxuICAgICAgICAxMTAsXG4gICAgICAgIDY4XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDc0LFxuICAgICAgICA4MCxcbiAgICAgICAgMjEsXG4gICAgICAgIDE2MSxcbiAgICAgICAgOTIsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMjUxLFxuICAgICAgICAxNDksXG4gICAgICAgIDc1LFxuICAgICAgICAyNDIsXG4gICAgICAgIDExLFxuICAgICAgICA0NSxcbiAgICAgICAgNjYsXG4gICAgICAgIDE3LFxuICAgICAgICAyMjksXG4gICAgICAgIDczLFxuICAgICAgICAyMDksXG4gICAgICAgIDQ3LFxuICAgICAgICA3MCxcbiAgICAgICAgMjIyLFxuICAgICAgICAyMzAsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMjM0LFxuICAgICAgICAyMTIsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMjMzLFxuICAgICAgICAzMSxcbiAgICAgICAgNTYsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMTUwLFxuICAgICAgICAyNTAsXG4gICAgICAgIDg0XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDExMixcbiAgICAgICAgICAxNzEsXG4gICAgICAgICAgMjQ3LFxuICAgICAgICAgIDE2MCxcbiAgICAgICAgICAxMixcbiAgICAgICAgICA5OCxcbiAgICAgICAgICAxMSxcbiAgICAgICAgICAyMDksXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDg5LFxuICAgICAgICAgIDIwNCxcbiAgICAgICAgICAxMjksXG4gICAgICAgICAgMjEzLFxuICAgICAgICAgIDEwNSxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICA0NyxcbiAgICAgICAgICA5NixcbiAgICAgICAgICAyMzQsXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDExMixcbiAgICAgICAgICA0MSxcbiAgICAgICAgICAyNDYsXG4gICAgICAgICAgODIsXG4gICAgICAgICAgMjEyLFxuICAgICAgICAgIDEzNSxcbiAgICAgICAgICA0LFxuICAgICAgICAgIDE3MCxcbiAgICAgICAgICAxMDgsXG4gICAgICAgICAgMTQxLFxuICAgICAgICAgIDExNSxcbiAgICAgICAgICAyNDEsXG4gICAgICAgICAgNzZcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNzksXG4gICAgICAgICAgMjQxLFxuICAgICAgICAgIDE0LFxuICAgICAgICAgIDMsXG4gICAgICAgICAgMTY1LFxuICAgICAgICAgIDEyOCxcbiAgICAgICAgICA0MSxcbiAgICAgICAgICA2NixcbiAgICAgICAgICA0MixcbiAgICAgICAgICA5NCxcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgNDYsXG4gICAgICAgICAgMjA1LFxuICAgICAgICAgIDIwMyxcbiAgICAgICAgICAxODMsXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDE4OSxcbiAgICAgICAgICA4NixcbiAgICAgICAgICAyMDgsXG4gICAgICAgICAgMjUyLFxuICAgICAgICAgIDI0OSxcbiAgICAgICAgICAyNSxcbiAgICAgICAgICAyMjUsXG4gICAgICAgICAgMTE3LFxuICAgICAgICAgIDIyOSxcbiAgICAgICAgICA0NixcbiAgICAgICAgICAyMjUsXG4gICAgICAgICAgMjQ3LFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICAxMjksXG4gICAgICAgICAgNjBcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAzNyxcbiAgICAgICAgMSxcbiAgICAgICAgNzIsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMTE1LFxuICAgICAgICAxNzUsXG4gICAgICAgIDIwMixcbiAgICAgICAgMTc1LFxuICAgICAgICAyMzIsXG4gICAgICAgIDEzNSxcbiAgICAgICAgNzUsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMTc2LFxuICAgICAgICA4MixcbiAgICAgICAgODQsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMjIwLFxuICAgICAgICAxNzIsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTgwLFxuICAgICAgICAxNTQsXG4gICAgICAgIDkyLFxuICAgICAgICAxODMsXG4gICAgICAgIDcyLFxuICAgICAgICA0LFxuICAgICAgICA3MyxcbiAgICAgICAgMTU4LFxuICAgICAgICA4MCxcbiAgICAgICAgMTE0LFxuICAgICAgICAxNzYsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMTg1LFxuICAgICAgICAxOTUsXG4gICAgICAgIDEwOSxcbiAgICAgICAgOTIsXG4gICAgICAgIDcyLFxuICAgICAgICAxNzAsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMjEzLFxuICAgICAgICAxMTAsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTg3LFxuICAgICAgICA0OSxcbiAgICAgICAgMTYxLFxuICAgICAgICA5MyxcbiAgICAgICAgMTQ0LFxuICAgICAgICA0MCxcbiAgICAgICAgMTg3LFxuICAgICAgICAxNjksXG4gICAgICAgIDEzMixcbiAgICAgICAgMjA1LFxuICAgICAgICAyMTAsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTI3LFxuICAgICAgICAxOTMsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMTMxLFxuICAgICAgICAyMTAsXG4gICAgICAgIDEzLFxuICAgICAgICAxNDksXG4gICAgICAgIDE0LFxuICAgICAgICAyNDEsXG4gICAgICAgIDEyMCxcbiAgICAgICAgOVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMTUzLFxuICBcImFkdlNlY3JldEtleVwiOiBcIllxc3lXdFJjNyswNTZOaGRhWjZsQk44dFpXVE5OK0VTZHQzOFhkWVFpSUk9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMCxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIm1sQmFGQTJBVDJlWnd2bDI5ZXVVWFFcIixcbiAgXCJwaG9uZUlkXCI6IFwiYzI0NzU2MDctNmQxNS00MzZkLThlY2UtODVkMmMzMjRkOTg5XCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDM1LFxuICAgICAgMjEwLFxuICAgICAgMTY0LFxuICAgICAgODgsXG4gICAgICA2OCxcbiAgICAgIDkzLFxuICAgICAgNzQsXG4gICAgICA0MixcbiAgICAgIDIxNyxcbiAgICAgIDYsXG4gICAgICAyMDcsXG4gICAgICAyNixcbiAgICAgIDIyLFxuICAgICAgMTc1LFxuICAgICAgMTcsXG4gICAgICAxMTksXG4gICAgICAxNzgsXG4gICAgICAxODYsXG4gICAgICAxMjUsXG4gICAgICAxOTFcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiBmYWxzZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDEzNixcbiAgICAgIDM5LFxuICAgICAgNzAsXG4gICAgICAxMDAsXG4gICAgICA5OCxcbiAgICAgIDIyNSxcbiAgICAgIDExLFxuICAgICAgNzQsXG4gICAgICA4NyxcbiAgICAgIDU3LFxuICAgICAgMTc1LFxuICAgICAgNDcsXG4gICAgICAyNTAsXG4gICAgICA5OCxcbiAgICAgIDE2NCxcbiAgICAgIDE3MyxcbiAgICAgIDE0OSxcbiAgICAgIDE1OCxcbiAgICAgIDIyMixcbiAgICAgIDE2XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDSTdkZ1pvQkVKai9uTE1HR0FzZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJCWFk4SnhzMGhlV1Y1NS9RSDNmMmN0cVZzdzdOZjNhM000cWRLZm54ZDBrPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIjUrTmYyRG9kNXJNQWFKMHpMc3VVYTRibjhpOTZCaGFHZFp1TFQxdjhjUk9nR3lkb3VucEkzVlBJMStkeWxDUUkvejN1QXAzZEZ6L2VEOC8wSGtBS0NRPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcImQ1L295R0ZicmJKb3ROK3EzR2lpRFN4ZFR3ZjJndWM5YVNxNCtDdVlPRTBVNStTZEJHUFdGWnhHaDhETUJ3NTRxTUkyNFZnSGw4ZFVJQjRTVXRiaENRPT1cIlxuICB9LFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjc4NDI5MzAyNTU6MTJAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcIm5hbWVcIjogXCJodWhcIixcbiAgICBcImxpZFwiOiBcIjUyMzMwMzY4MTAyNjI5OjEyQGxpZFwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjc4NDI5MzAyNTU6MTJAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICA1LFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICA2MCxcbiAgICAgICAgICAzOSxcbiAgICAgICAgICAyNyxcbiAgICAgICAgICA1MixcbiAgICAgICAgICAxMzMsXG4gICAgICAgICAgMjI5LFxuICAgICAgICAgIDE0OSxcbiAgICAgICAgICAyMzEsXG4gICAgICAgICAgMTU5LFxuICAgICAgICAgIDIwOCxcbiAgICAgICAgICAzMSxcbiAgICAgICAgICAxMTksXG4gICAgICAgICAgMjQ2LFxuICAgICAgICAgIDExNCxcbiAgICAgICAgICAyMTgsXG4gICAgICAgICAgMTQ5LFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAxNCxcbiAgICAgICAgICAyMDUsXG4gICAgICAgICAgMTI3LFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAxODMsXG4gICAgICAgICAgNTEsXG4gICAgICAgICAgMTM4LFxuICAgICAgICAgIDE1NyxcbiAgICAgICAgICA0MSxcbiAgICAgICAgICAyNDksXG4gICAgICAgICAgMjQxLFxuICAgICAgICAgIDExOSxcbiAgICAgICAgICA3M1xuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwic21iYVwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzE4MDQyNTI0LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBUEhKXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFQSEguanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJ1RTdSUEptM0hFNFFzNHJVejl4ak1TNThqWmZLbEVBOTRwanlPMXRxK2ZFPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjMyMjk4OTcxMCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBUEhJLmpzb24iOiAie1wia2V5RGF0YVwiOlwiWnVmUkx0bUlrQTEreHFQSXJkTEdXWmlJbnNsbFEzNzh6cW9DbE1hSkl6UT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjozMjI5ODk3MTAsXCJjdXJyZW50SW5kZXhcIjozLFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsMl19LFwidGltZXN0YW1wXCI6XCIxNzE0NTc5ODU2MDc3XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBUEhKLmpzb24iOiAie1wia2V5RGF0YVwiOlwialgwUTFweFQxbFQ4dlRJM2NYYk5wTHBiMHprcXY5TWxHSHMyWitDYWtrRT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjozMjI5ODk3MTAsXCJjdXJyZW50SW5kZXhcIjo0LFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsMl19LFwidGltZXN0YW1wXCI6XCIxNzE2MDI4Mzc3MTk5XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBUEhLLmpzb24iOiAie1wia2V5RGF0YVwiOlwiZVovZlRXNFpNTm1IWmdJL0U4UFdGcWFXMFpxMW94bTZvaHlqYXlMZVp6OD1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjozMjI5ODk3MTAsXCJjdXJyZW50SW5kZXhcIjo1LFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsNV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBUEhMLmpzb24iOiAie1wia2V5RGF0YVwiOlwiRkJmMWxQUUVadjRIVWNaUEVTaDV1M0JWQXpHR2hlajl4VmtQaGh2V2NWVT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjozMjI5ODk3MTAsXCJjdXJyZW50SW5kZXhcIjo2LFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsNV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBUEhNLmpzb24iOiAie1wia2V5RGF0YVwiOlwib3RiWGY3YUpTZ2FNUDJuQ1FTMnJ3dkl1SXB1Z0hySTJ4R3FGR2g4L2w5Yz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjozMjI5ODk3MTAsXCJjdXJyZW50SW5kZXhcIjo3LFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsNV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBUEhOLmpzb24iOiAie1wia2V5RGF0YVwiOlwibWhjek80NEZ4SUx0a1E3S0VqbHdhUjVrM0lwZllYMm9zaDNHQXYzRjA5Zz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjozMjI5ODk3MTAsXCJjdXJyZW50SW5kZXhcIjo4LFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsNV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBUEhPLmpzb24iOiAie1wia2V5RGF0YVwiOlwid2h4bnYyeHVhNnowTmUxbWlIVjBHSG9HdHQxLzFDazI5YzFldTZTYWY0az1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjozMjI5ODk3MTAsXCJjdXJyZW50SW5kZXhcIjo5LFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsNV19LFwidGltZXN0YW1wXCI6XCIxNzE3ODcxNjczODk5XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBUEhQLmpzb24iOiAie1wia2V5RGF0YVwiOlwiMGVSQkZKQkNxZnUreHltK2dyMFVydlptZkkxd0NEckFpOFJrVDVqSTZOYz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjozMjI5ODk3MTAsXCJjdXJyZW50SW5kZXhcIjoxMCxcImRldmljZUluZGV4ZXNcIjpbMCwxLDVdfSxcInRpbWVzdGFtcFwiOlwiMTcxNzg3MjMzMTQ2NVwifSIKfQ=="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || "!",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.7",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "cartifoundthis",
  packname: process.env.PACK_NAME || "seyuhhh",
  botname : process.env.BOT_NAME  || "Carti2.0",
  ownername:process.env.OWNER_NAME|| "kreep4pres*🍄",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
